#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
plugins=(ssh-agent)

# ssh-agent
if [[ "$SSH_AGENT_PID" == "" ]]; then
    eval $(ssh-agent)
fi
ssh-add -l >/dev/null || alias ssh='ssh-add -l >/dev/null || ssh-add && unalias ssh; ssh'

export SSH_ASKPASS="/usr/bin/ksshaskpass"
export ANDROID_HOME=/opt/android-sdk
alias pac=pacaur
alias fastboot='sudo fastboot'
alias adb='sudo adb'
alias pip='sudo pip'
